services:
  db_test:
    image: postgres:16
    container_name: portafolio_postgres_test
    environment:
      POSTGRES_USER: portafolio
      POSTGRES_PASSWORD: portafolio
      POSTGRES_DB: portafolio_test
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portafolio -d portafolio_test"]
      interval: 3s
      timeout: 3s
      retries: 20
